spring.application.name=mail
# Email Configuration (Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=na
spring.mail.password=3C3Chandu@
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Your email to receive contact form messages
app.contact.recipient-email=chandruravik3@gmail.com

# Server configuration
server.port=8080
